Migrate to github apps (#3409)
* Migrate to github apps

* Wip

* Review changes

diff --git a/.github/workflows/promote-keb-to-dev.yaml b/.github/workflows/promote-keb-to-dev.yaml
--- a/.github/workflows/promote-keb-to-dev.yaml
+++ b/.github/workflows/promote-keb-to-dev.yaml
@@ -2,11 +2,8 @@ name: Promote KEB to dev
 
 env:
   MANAGEMENT_PLANE_CHARTS:  "https://${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}.git"
-  MANAGEMENT_PLANE_CHARTS_WITH_USER: "https://${{ vars.GIT_USER_NAME }}:${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}.git"
   KEB_API_URL: "https://api.github.com/repos/kyma-project/kyma-environment-broker"
   KEB_RELEASES_URL: "https://github.com/kyma-project/kyma-environment-broker/releases"
-  # needed by gh cli for GitHub enterprise
-  GH_ENTERPRISE_TOKEN: ${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}
 
 on:
   workflow_dispatch:
@@ -30,11 +27,21 @@ jobs:
     steps:
       - name: Validate required environment variables
         run: |
-          [ -z "${{ vars.GIT_USER_EMAIL }}" ] && echo "GIT_USER_EMAIL is required" && exit 1 
-          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1 
-          [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1 
-          [ -z "${{ vars.MP_CHARTS_REPO_NAME }}" ] && echo "MP_CHARTS_REPO_NAME is required" && exit 1 
+          [ -z "${{ vars.GIT_USER_EMAIL }}" ] && echo "GIT_USER_EMAIL is required" && exit 1
+          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1
+          [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1
+          [ -z "${{ vars.MP_CHARTS_REPO_NAME }}" ] && echo "MP_CHARTS_REPO_NAME is required" && exit 1
           echo "Validated"
+
+      - name: Generate enterprise bot token
+        id: enterprise-bot-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ vars.GOPHER_TOOLS_BOT_APP_ID }}
+          private-key: ${{ secrets.GOPHER_TOOLS_BOT_APP_PRIVATE_KEY }}
+          github-api-url: https://${{ vars.GH_TOOLS_HOST }}/api/v3
+          owner: kyma
+          repositories: management-plane-charts,release-management
 
       - name: Use default (latest) Release Tag
         if: inputs.releaseTag == 'use latest release'
@@ -64,11 +71,11 @@ jobs:
 
       - name: Setup git and clone repo
         env:
-          GH_TOKEN: ${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}
+          MANAGEMENT_PLANE_CHARTS_WITH_USER: "https://x-access-token:${{ steps.enterprise-bot-token.outputs.token }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}.git"
         run: |
           git config --global user.email ${{ vars.GIT_USER_EMAIL }}
           git config --global user.name ${{ vars.GIT_USER_NAME }}
-          git clone ${MANAGEMENT_PLANE_CHARTS_WITH_USER}
+          git clone "${MANAGEMENT_PLANE_CHARTS_WITH_USER}"
 
       - name: Setup python
         uses: actions/setup-python@v6
@@ -101,16 +108,19 @@ jobs:
 
       - name: Commit and push changes
         working-directory: management-plane-charts
+        env:
+          MANAGEMENT_PLANE_CHARTS_WITH_USER: "https://x-access-token:${{ steps.enterprise-bot-token.outputs.token }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}.git"
         run: |
           git add .
           git commit -m "Bump keb to ${TAG}"
-          git remote set-url origin ${MANAGEMENT_PLANE_CHARTS_WITH_USER}
+          git remote set-url origin "${MANAGEMENT_PLANE_CHARTS_WITH_USER}"
           git push origin ${BRANCH_NAME}
 
       - name: Create PR if needed
         working-directory: management-plane-charts
         env:
           MANAGEMENT_PLANE_CHARTS_REPO_URL: "https://${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}"
+          GH_ENTERPRISE_TOKEN: ${{ steps.enterprise-bot-token.outputs.token }}
           # needed by gh cli for GitHub enterprise
           GH_HOST: ${{ vars.GH_TOOLS_HOST }}
         run: |
@@ -130,6 +140,7 @@ jobs:
         env:
           MANAGEMENT_PLANE_CHARTS_REPO_URL: "https://${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MP_CHARTS_REPO_NAME }}"
           RELEASE_MANAGEMENT_REPO_URL: "https://${{ vars.GH_TOOLS_HOST }}/kyma/release-management"
+          GH_ENTERPRISE_TOKEN: ${{ steps.enterprise-bot-token.outputs.token }}
           # needed by gh cli for GitHub enterprise
           GH_HOST: ${{ vars.GH_TOOLS_HOST }}
         run: |
