Wip

diff --git a/.github/workflows/promote-keb-to-dev.yaml b/.github/workflows/promote-keb-to-dev.yaml
--- a/.github/workflows/promote-keb-to-dev.yaml
+++ b/.github/workflows/promote-keb-to-dev.yaml
@@ -28,6 +28,8 @@ jobs:
       - name: Validate required environment variables
         run: |
           [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1
+          [ -z "${{ vars.GIT_TOOLS_USER_EMAIL }}" ] && echo "GIT_TOOLS_USER_EMAIL is required" && exit 1
+          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1
           [ -z "${{ vars.MP_CHARTS_REPO_NAME }}" ] && echo "MP_CHARTS_REPO_NAME is required" && exit 1
           echo "Validated"
 
diff --git a/.github/workflows/sync-docs-toc.yml b/.github/workflows/sync-docs-toc.yml
--- a/.github/workflows/sync-docs-toc.yml
+++ b/.github/workflows/sync-docs-toc.yml
@@ -42,8 +42,10 @@ jobs:
     steps:
       - name: Validate required variables
         run: |
-          [ -z "${{ vars.GH_TOOLS_HOST }}" ]        && echo "GH_TOOLS_HOST is required"        && exit 1
-          [ -z "${{ vars.PK_RUNTIME_REPO_NAME }}" ] && echo "PK_RUNTIME_REPO_NAME is required" && exit 1
+          [ -z "${{ vars.GH_TOOLS_HOST }}" ]             && echo "GH_TOOLS_HOST is required"             && exit 1
+          [ -z "${{ vars.GIT_TOOLS_USER_EMAIL }}" ]      && echo "GIT_TOOLS_USER_EMAIL is required"      && exit 1
+          [ -z "${{ vars.GIT_USER_NAME }}" ]             && echo "GIT_USER_NAME is required"             && exit 1
+          [ -z "${{ vars.PK_RUNTIME_REPO_NAME }}" ]      && echo "PK_RUNTIME_REPO_NAME is required"      && exit 1
           echo "Validated"
 
       - name: Generate enterprise bot token
