wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -390,3 +390,126 @@ jobs:
           echo "Success rate of update requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
           
           scripts/generate_metrics.sh
+          
+  run-updates-on-a-single-instance-test:
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    strategy:
+      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Prepare K3s cluster and docker registry
+        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"
+
+      - name: Prepare values.yaml
+        run: |
+          yq e ".update.maxStepProcessingTime = \"${{ inputs.update-max-step-processing-time }}\"" -i resources/keb/values.yaml
+          yq e ".update.workersAmount = ${{ inputs.update-workers-amount }}" -i resources/keb/values.yaml
+
+      - name: Install KEB chart
+        run: |
+          if [ "${{ inputs.release }}" == "true" ]; then
+            make install VERSION=${{ inputs.version }}
+          else
+            make install VERSION=PR-${{ inputs.version }}
+          fi
+
+      - name: Populate database
+        run: |
+          DB_NAME=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-db-name}" | base64 -d)
+          DB_USER=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-username}" | base64 -d)
+          DB_PASS=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-password}" | base64 -d)
+
+          kubectl port-forward -n kcp-system deployment/postgres 5432:5432 &
+          PORT_FORWARD_PID=$!
+          echo $PORT_FORWARD_PID
+          sleep 5
+
+          PGPASSWORD=$DB_PASS psql -h localhost -p 5432 -U $DB_USER -d $DB_NAME -f resources/installation/migrations/populate_performance_tests_database.up.sql
+
+          kill $PORT_FORWARD_PID
+
+      - name: Provision the instance
+        run: |
+          kubectl port-forward -n kcp-system deployment/kcp-kyma-environment-broker 8080:8080 5432:5432 &
+          sleep 5
+
+          curl --request PUT \
+            --url http://localhost:8080/oauth/v2/service_instances/azure-cluster \
+            --header "Content-Type: application/json" \
+            --header "X-Broker-API-Version: 2.16" \
+            --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"4deee563-e5ec-4731-b9b1-53b42d855f0c\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"name\":\"azure-cluster\",\"region\":\"northeurope\"}}"
+
+      - name: Simulate KIM
+        timeout-minutes: 60
+        env:
+          KIM_DELAY_SECONDS: 0
+        run: |
+          scripts/simulate_kim.sh
+
+          INSTANCE_JSON=$(curl --request GET \
+            --url "http://localhost:8080/runtimes?instance_id=azure-cluster" \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16')
+          INSTANCE_STATE=$(echo "$INSTANCE_JSON" | jq '.data[0].status.state')
+
+          if [ "$INSTANCE_STATE" = "succeeded" ]; then
+            echo "Assertion passed: state is $INSTANCE_STATE"
+          else
+            echo "Assertion failed: state is not 'succeeded'. Actual value: $INSTANCE_STATE"
+            exit 1
+          fi
+
+      - name: Start metrics collector
+        run: |
+          nohup bash scripts/monitor_metrics.sh > /dev/null 2>&1 &
+          echo $! > /tmp/metrics_pid  
+
+      - name: Update the instance
+        timeout-minutes: 60
+        run: |
+          for i in $(seq 1 100); do
+            max=$((i + 4))
+            echo "Updating instance: Iteration $i with autoScalerMax=$max"
+          
+            curl --silent --show-error --fail --request PATCH \
+              --url "http://localhost:8080/oauth/v2/service_instances/azure-cluster?accepts_incomplete=true" \
+              --header "Content-Type: application/json" \
+              --header "X-Broker-API-Version: 2.16" \
+              --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"4deee563-e5ec-4731-b9b1-53b42d855f0c\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"autoScalerMax\":$max}}" > /dev/null 2>&1
+          done
+          
+          while true; do
+            INSTANCE_STATE=$(curl --request GET \
+              --url "http://localhost:8080/runtimes?instance_id=azure-cluster" \
+              --header 'Content-Type: application/json' \
+              --header 'X-Broker-API-Version: 2.16' | jq '.data[0].status.state')
+
+            if [ "$INSTANCE_STATE" = "succeeded" ]; then
+              echo "Instance is updated. Done."
+              break
+            fi
+
+            sleep 10
+          done
+
+      - name: Fetch metrics
+        run: |
+          sleep 15
+
+          METRICS=$(curl -s http://localhost:8080/metrics)
+          SUCCEEDED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operation_result.*plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c".*state="succeeded".*type="update"' | wc -l | xargs)
+          SUCCEEDED_TOTAL=${SUCCEEDED_TOTAL:-0}
+          FAILED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operation_result.*plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c".*state="failed".*type="update"' | wc -l | xargs)
+          FAILED_TOTAL=${FAILED_TOTAL:-0}
+          TOTAL=$(echo "$SUCCEEDED_TOTAL + $FAILED_TOTAL" | bc)
+          if [ "$TOTAL" -eq 0 ]; then
+            SUCCESS_RATE=0
+          else
+            SUCCESS_RATE=$(awk "BEGIN {printf \"%.2f\", ($SUCCEEDED_TOTAL / $TOTAL) * 100}")
+          fi
+          echo "Success rate of update requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
+
+          scripts/generate_metrics.sh
