wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -239,7 +239,7 @@ jobs:
           done)
           echo "Maximum duration of provisioning requests: $MAX_PROVISIONING_DURATION minutes" >> $GITHUB_STEP_SUMMARY
           
-          scripts/generate_metrics.sh
+          scripts/generate_charts.sh
 
   run-concurrent-update-test:
     runs-on: ubuntu-latest
@@ -351,7 +351,6 @@ jobs:
             fi
           
             echo "$RESPONSE" | jq -r '.data[].instanceID' | while read -r INSTANCE_ID; do
-              echo "Updating instance: $INSTANCE_ID"
               curl --silent --show-error --fail --request PATCH \
                 --url "http://localhost:8080/oauth/v2/service_instances/$INSTANCE_ID?accepts_incomplete=true" \
                 --header "Content-Type: application/json" \
@@ -393,7 +392,7 @@ jobs:
           fi
           echo "Success rate of update requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
           
-          scripts/generate_metrics.sh
+          scripts/generate_charts.sh
           
   run-updates-on-a-single-instance-test:
     runs-on: ubuntu-latest
@@ -476,7 +475,6 @@ jobs:
         run: |
           max=5
           for i in $(seq 1 ${{ inputs.updates-number }}); do
-            echo "Updating instance: Iteration $i with autoScalerMax=$max"
             curl --silent --show-error --fail --request PATCH \
               --url "http://localhost:8080/oauth/v2/service_instances/azure-cluster?accepts_incomplete=true" \
               --header "Content-Type: application/json" \
@@ -520,4 +518,178 @@ jobs:
           fi
           echo "Success rate of update requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
 
-          scripts/generate_metrics.sh
+          scripts/generate_charts.sh
+          
+  run-concurrent-deprovisoning-test:
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    strategy:
+      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Prepare K3s cluster and docker registry
+        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"
+
+      - name: Prepare values.yaml
+        run: |
+          yq e ".provisioning.maxStepProcessingTime = \"10s\"" -i resources/keb/values.yaml
+          yq e ".provisioning.workersAmount = 100" -i resources/keb/values.yaml
+          yq e ".deprovisioning.maxStepProcessingTime = \"${{ inputs.deprovisioning-max-step-processing-time }}\"" -i resources/keb/values.yaml
+          yq e ".deprovisioning.workersAmount = ${{ inputs.deprovisioning-workers-amount }}" -i resources/keb/values.yaml
+
+      - name: Install KEB chart
+        run: |
+          if [ "${{ inputs.release }}" == "true" ]; then
+            make install VERSION=${{ inputs.version }}
+          else
+            make install VERSION=PR-${{ inputs.version }}
+          fi
+
+      - name: Populate database
+        run: |
+          DB_NAME=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-db-name}" | base64 -d)
+          DB_USER=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-username}" | base64 -d)
+          DB_PASS=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-password}" | base64 -d)
+
+          kubectl port-forward -n kcp-system deployment/postgres 5432:5432 &
+          PORT_FORWARD_PID=$!
+          echo $PORT_FORWARD_PID
+          sleep 5
+
+          PGPASSWORD=$DB_PASS psql -h localhost -p 5432 -U $DB_USER -d $DB_NAME -f resources/installation/migrations/populate_performance_tests_database.up.sql
+
+          kill $PORT_FORWARD_PID
+
+      - name: Provision instances
+        run: |
+          kubectl port-forward -n kcp-system deployment/kcp-kyma-environment-broker 8080:8080 5432:5432 &
+          sleep 5
+
+          seq 1 ${{ inputs.instances-number }} | xargs -n1 -P8 -I{} bash -c '
+            uid=$(uuidgen)
+            curl --silent --show-error --fail --request PUT \
+              --url http://localhost:8080/oauth/v2/service_instances/$uid \
+              --header "Content-Type: application/json" \
+              --header "X-Broker-API-Version: 2.16" \
+              --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"4deee563-e5ec-4731-b9b1-53b42d855f0c\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"name\":\"azure-cluster\",\"region\":\"northeurope\"}}" > /dev/null 2>&1
+          '
+
+          TOTAL_COUNT=$(curl --request GET \
+            --url http://localhost:8080/runtimes?plan=azure \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
+
+          if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+            exit 1
+          fi
+
+      - name: Simulate KIM
+        timeout-minutes: 60
+        env:
+          KIM_DELAY_SECONDS: 0
+        run: |
+          scripts/simulate_kim.sh
+
+          RESPONSE_JSON=$(curl --request GET \
+            --url "http://localhost:8080/runtimes?plan=azure&state=succeeded" \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16')
+          SUCCEEDED_TOTAL_COUNT=$(echo "$RESPONSE_JSON" | jq .totalCount)
+
+          if [ "$SUCCEEDED_TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $SUCCEEDED_TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $SUCCEEDED_TOTAL_COUNT"
+            exit 1
+          fi
+
+      - name: Start metrics collector
+        run: |
+          nohup bash scripts/monitor_metrics.sh > /dev/null 2>&1 &
+          echo $! > /tmp/metrics_pid  
+
+      - name: Deprovision instances
+        timeout-minutes: 60
+        run: |
+          PAGE=1
+
+          while true; do
+            RESPONSE=$(curl --silent --show-error --fail --request GET \
+              --url "http://localhost:8080/runtimes?plan=azure&page=$PAGE" \
+              --header 'Content-Type: application/json' \
+              --header 'X-Broker-API-Version: 2.16')
+
+            COUNT=$(echo "$RESPONSE" | jq '.count')
+            if [ "$COUNT" -eq 0 ]; then
+              break
+            fi
+
+            echo "$RESPONSE" | jq -r '.data[].instanceID' | while read -r INSTANCE_ID; do
+              curl --silent --show-error --fail --request DELETE \
+                --url "http://localhost:8080/oauth/v2/service_instances/$INSTANCE_ID?accepts_incomplete=true&service_id=47c9dcbf-ff30-448e-ab36-d3bad66ba281&plan_id=4deee563-e5ec-4731-b9b1-53b42d855f0c" \
+                --header "Content-Type: application/json" \
+                --header "X-Broker-API-Version: 2.16" \
+                --data '{"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281","plan_id":"4deee563-e5ec-4731-b9b1-53b42d855f0c","context":{"globalaccount_id":"2f5011af-2fd3-44ba-ac60-eeb1148c2995","subaccount_id":"8b9a0db4-9aef-4da2-a856-61a4420b66fd","user_id":"user@email.com"}}' > /dev/null 2>&1
+            done
+
+            PAGE=$((PAGE + 1))
+          done
+
+          while true; do
+            DEPROVISIONING_COUNT=$(curl --request GET \
+              --url "http://localhost:8080/runtimes?plan=azure&state=deprovisioning" \
+              --header 'Content-Type: application/json' \
+              --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
+
+            if [ "$DEPROVISIONING_COUNT" -eq 0 ]; then
+              echo "All instances are deprovisioned. Done."
+              break
+            fi
+
+            sleep 10
+          done
+
+      - name: Fetch metrics
+        run: |
+          METRICS=$(curl -s http://localhost:8080/metrics)
+          
+          SUCCEEDED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operations_deprovisioning_succeeded_total{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          SUCCEEDED_TOTAL=${SUCCEEDED_TOTAL:-0}
+          FAILED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operations_deprovisioning_failed_total{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          FAILED_TOTAL=${FAILED_TOTAL:-0}
+          TOTAL=$(echo "$SUCCEEDED_TOTAL + $FAILED_TOTAL" | bc)
+          if [ "$TOTAL" -eq 0 ]; then
+            SUCCESS_RATE=0
+          else
+            SUCCESS_RATE=$(awk "BEGIN {printf \"%.2f\", ($SUCCEEDED_TOTAL / $TOTAL) * 100}")
+          fi
+          echo "Success rate of deprovisioning requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
+          
+          DEPROVISIONING_DURATION=$(echo "$METRICS" | grep 'kcp_keb_v2_deprovisioning_duration_minutes_sum{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          DEPROVISIONING_DURATION=${DEPROVISIONING_DURATION:-0}
+          DEPROVISIONING_COUNT=$(echo "$METRICS" | grep 'kcp_keb_v2_deprovisioning_duration_minutes_count{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          DEPROVISIONING_COUNT=${DEPROVISIONING_COUNT:-0}
+          if [ "$DEPROVISIONING_COUNT" -eq 0 ]; then
+            AVG_DEPROVISIONING_DURATION=0
+          else
+            AVG_DEPROVISIONING_DURATION=$(awk "BEGIN {printf \"%.2f\", ($DEPROVISIONING_DURATION / $DEPROVISIONING_COUNT)}")
+          fi
+          echo "Average duration of deprovisioning requests: $AVG_DEPROVISIONING_DURATION minutes" >> $GITHUB_STEP_SUMMARY
+          
+          DEPROVISIONING_DURATION_BUCKETS=$(echo "$METRICS" | grep 'kcp_keb_v2_deprovisioning_duration_minutes_bucket{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"')
+          INF_TOTAL=$(echo "$DEPROVISIONING_DURATION_BUCKETS" | grep 'le="+Inf"' | awk '{print $2}')
+          MAX_DEPROVISIONING_DURATION=$(echo "$DEPROVISIONING_DURATION_BUCKETS" | grep -v 'le="\+Inf"' | sed -n 's/.*le="\([^"]*\)"} \([0-9]*\)/\1 \2/p' | \
+          while read le count; do
+            if [ "$count" -eq "$INF_TOTAL" ]; then
+              echo "$le"
+              break
+            fi
+          done)
+          echo "Maximum duration of deprovisioning requests: $MAX_DEPROVISIONING_DURATION minutes" >> $GITHUB_STEP_SUMMARY
+
+          scripts/generate_charts.sh
