Add wait step for provisioning status

diff --git a/.github/workflows/run-keb-chart-install-tests-reusable.yaml b/.github/workflows/run-keb-chart-install-tests-reusable.yaml
--- a/.github/workflows/run-keb-chart-install-tests-reusable.yaml
+++ b/.github/workflows/run-keb-chart-install-tests-reusable.yaml
@@ -126,3 +126,22 @@ jobs:
         run: |
           make set-runtime-state RUNTIME_ID=$RUNTIME_ID STATE=Ready
           make set-kyma-state KYMA_ID=$RUNTIME_ID STATE=Ready
+
+      - name: Wait for provisioning to finish
+        run: |
+          while true; do
+            STATUS=$(curl --request GET \
+              --url http://localhost:8080/runtimes \
+              --header 'Content-Type: application/json' \
+              --header 'X-Broker-API-Version: 2.16' | jq -r '.data[] | select(.instanceID=="azure-cluster") | .status.provisioning.state')
+
+            echo "Current provisioning status: $STATUS"
+            if [ "$STATUS" == "succeeded" ]; then
+              echo "Provisioning succeeded."
+              break
+            elif [ "$STATUS" == "failed" ]; then
+              echo "Provisioning failed."
+              exit 1
+            fi
+            sleep 10
+          done
