wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -1048,6 +1048,24 @@ jobs:
           fetch_and_measure 100000 100
 
           echo "</div>" >> "$GITHUB_STEP_SUMMARY"
+          
+          SUCCESS_COUNT=0
+          for i in {1..100}; do
+            STATUS_CODE=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+              --request GET \
+              --url "http://localhost:8080/runtimes" \
+              --header 'Content-Type: application/json' \
+              --header 'X-Broker-API-Version: 2.16')
+            if [[ "$STATUS_CODE" == "200" ]]; then
+              ((SUCCESS_COUNT++))
+            fi
+          done
+          SUCCESS_RATE=$((SUCCESS_COUNT * 100 / 100))
+          echo "Success rate of runtimes requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
+          if [[ "$SUCCESS_RATE" != "100" ]]; then
+            echo "Error: SUCCESS_RATE is $SUCCESS_RATE, expected 100"
+            exit 1
+          fi
 
       - name: Fetch metrics
         run: scripts/generate_charts.sh
