Fix assertion

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -919,12 +919,12 @@ jobs:
             --header 'Content-Type: application/json' \
             --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
 
-          if [ "$TOTAL_COUNT" -eq "$((2 * ${{ inputs.instances-number }}))" ]; then
-            echo "Assertion passed: totalCount is $TOTAL_COUNT"
-          else
-            echo "Assertion failed: totalCount is not $((2 * ${{ inputs.instances-number }})). Actual value: $TOTAL_COUNT"
-            exit 1
-          fi
+            if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+              echo "Assertion passed: totalCount is $TOTAL_COUNT"
+            else
+              echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+              exit 1
+            fi
 
       - name: Simulate KIM (second round - provision)
         if: ${{ inputs.post-test-monitoring-minutes > 0 }}
