wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -152,6 +152,7 @@ jobs:
         run: |
           kubectl port-forward -n kcp-system deployment/kcp-kyma-environment-broker 8080:8080 5432:5432 &
           sleep 5
+          
           seq 1 ${{ inputs.instances-number }} | xargs -n1 -P20 -I{} bash -c '
             uid=$(uuidgen)
             curl --silent --show-error --fail --request PUT \
@@ -160,10 +161,15 @@ jobs:
               --header "X-Broker-API-Version: 2.16" \
               --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"4deee563-e5ec-4731-b9b1-53b42d855f0c\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"name\":\"azure-cluster\",\"region\":\"northeurope\"}}" > /dev/null 2>&1
           '
+          
+          TOTAL_COUNT=$(curl --request GET \
+            --url http://localhost:8080/runtimes?plan=azure \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
 
-      - name: Print runtimes
-        run: |
-          curl --request GET \
-          --url http://localhost:8080/runtimes \
-          --header 'Content-Type: application/json' \
-          --header 'X-Broker-API-Version: 2.16' | jq
+          if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+            exit 1
+          fi
