wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -22,7 +22,7 @@ on:
         type: number
       kim-delay-seconds:
         description: time to wait before transitioning the runtime CR to the Ready state
-        default: 120
+        default: 420
         type: number
       provisioning-max-step-processing-time:
         description: max time to process a step in provisioning queue
@@ -124,7 +124,7 @@ jobs:
       - name: Prepare K3s cluster and docker registry
         run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"
         
-      - name: Set provisioning workers amount
+      - name: Prepare values.yaml
         run: |
           yq e ".provisioning.maxStepProcessingTime = \"${{ inputs.provisioning-max-step-processing-time }}\"" -i resources/keb/values.yaml
           yq e ".provisioning.workersAmount = ${{ inputs.provisioning-workers-amount }}" -i resources/keb/values.yaml
@@ -184,7 +184,7 @@ jobs:
           fi
       
       - name: Simulate KIM
-        timeout-minutes: 45
+        timeout-minutes: 60
         env:
           KIM_DELAY_SECONDS: ${{ inputs.kim-delay-seconds }}
         run: scripts/simulate_kim.sh
@@ -275,3 +275,85 @@ jobs:
           echo "| Green | In use   |" >> "$GITHUB_STEP_SUMMARY"
           echo "</div>" >> "$GITHUB_STEP_SUMMARY"
           echo "" >> "$GITHUB_STEP_SUMMARY"
+
+  run-concurrent-update-test:
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    strategy:
+      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Prepare K3s cluster and docker registry
+        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"
+
+      - name: Prepare values.yaml
+        run: |
+          yq e ".provisioning.maxStepProcessingTime = 10s" -i resources/keb/values.yaml
+          yq e ".provisioning.workersAmount = 100" -i resources/keb/values.yaml
+
+      - name: Install KEB chart
+        run: |
+          if [ "${{ inputs.release }}" == "true" ]; then
+            make install VERSION=${{ inputs.version }}
+          else
+            make install VERSION=PR-${{ inputs.version }}
+          fi
+
+      - name: Populate database
+        run: |
+          DB_NAME=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-db-name}" | base64 -d)
+          DB_USER=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-username}" | base64 -d)
+          DB_PASS=$(kubectl get secret kcp-postgresql -n kcp-system -o jsonpath="{.data.postgresql-broker-password}" | base64 -d)
+
+          kubectl port-forward -n kcp-system deployment/postgres 5432:5432 &
+          PORT_FORWARD_PID=$!
+          echo $PORT_FORWARD_PID
+          sleep 5
+
+          PGPASSWORD=$DB_PASS psql -h localhost -p 5432 -U $DB_USER -d $DB_NAME -f resources/installation/migrations/populate_performance_tests_database.up.sql
+
+          kill $PORT_FORWARD_PID
+
+      - name: Provision multiple instances
+        run: |
+          seq 1 ${{ inputs.instances-number }} | xargs -n1 -P8 -I{} bash -c '
+            uid=$(uuidgen)
+            curl --silent --show-error --fail --request PUT \
+              --url http://localhost:8080/oauth/v2/service_instances/$uid \
+              --header "Content-Type: application/json" \
+              --header "X-Broker-API-Version: 2.16" \
+              --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"4deee563-e5ec-4731-b9b1-53b42d855f0c\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"name\":\"azure-cluster\",\"region\":\"northeurope\"}}" > /dev/null 2>&1
+          '
+
+          TOTAL_COUNT=$(curl --request GET \
+            --url http://localhost:8080/runtimes?plan=azure \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
+
+          if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+            exit 1
+          fi
+
+      - name: Simulate KIM
+        timeout-minutes: 60
+        env:
+          KIM_DELAY_SECONDS: 0
+        run: |
+          scripts/simulate_kim.sh
+          
+          TOTAL_COUNT=$(curl --request GET \
+            --url http://localhost:8080/runtimes?plan=azure&state=succeeded \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
+
+          if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+            exit 1
+          fi
