wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -353,7 +353,6 @@ jobs:
             --url "http://localhost:8080/runtimes?plan=azure&state=succeeded" \
             --header 'Content-Type: application/json' \
             --header 'X-Broker-API-Version: 2.16')
-  
           SUCCEEDED_TOTAL_COUNT=$(echo "$RESPONSE_JSON" | jq .totalCount)
 
           if [ "$SUCCEEDED_TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
@@ -362,6 +361,14 @@ jobs:
             echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $SUCCEEDED_TOTAL_COUNT"
             exit 1
           fi
+          
+      - name: Start background metrics collector
+        run: |
+          kubectl port-forward -n kcp-system deployment/kcp-kyma-environment-broker 8080:8080 5432:5432 &
+          sleep 5
+          
+          nohup bash scripts/monitor_metrics.sh > /dev/null 2>&1 &
+          echo $! > /tmp/metrics_pid  
         
       - name: Update instances
         run: |
@@ -384,8 +391,73 @@ jobs:
                 --url "http://localhost:8080/oauth/v2/service_instances/$INSTANCE_ID" \
                 --header "Content-Type: application/json" \
                 --header "X-Broker-API-Version: 2.16" \
-                --data '{"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281","plan_id":"4deee563-e5ec-4731-b9b1-53b42d855f0c","context":{"globalaccount_id":"2f5011af-2fd3-44ba-ac60-eeb1148c2995","subaccount_id":"8b9a0db4-9aef-4da2-a856-61a4420b66fd","user_id":"user@email.com"},"parameters":{"autoScalerMax":15}}' > /dev/null 2>&1 && echo "Updated $INSTANCE_ID"
+                --data '{"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281","plan_id":"4deee563-e5ec-4731-b9b1-53b42d855f0c","context":{"globalaccount_id":"2f5011af-2fd3-44ba-ac60-eeb1148c2995","subaccount_id":"8b9a0db4-9aef-4da2-a856-61a4420b66fd","user_id":"user@email.com"},"parameters":{"autoScalerMax":15}}' > /dev/null 2>&1
             done
           
             PAGE=$((PAGE + 1))
           done
+        
+      - name: Fetch metrics from KEB
+        run: |
+          METRICS=$(curl -s http://localhost:8080/metrics)
+
+          SUCCEEDED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operations_updating_succeeded_total{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          SUCCEEDED_TOTAL=${SUCCEEDED_TOTAL:-0}
+          FAILED_TOTAL=$(echo "$METRICS" | grep 'kcp_keb_v2_operations_updating_failed_total{plan_id="4deee563-e5ec-4731-b9b1-53b42d855f0c"}' | awk '{print $2}')
+          FAILED_TOTAL=${FAILED_TOTAL:-0}
+          TOTAL=$(echo "$SUCCEEDED_TOTAL + $FAILED_TOTAL" | bc)
+          if [ "$TOTAL" -eq 0 ]; then
+            SUCCESS_RATE=0
+          else
+            SUCCESS_RATE=$(awk "BEGIN {printf \"%.2f\", ($SUCCEEDED_TOTAL / $TOTAL) * 100}")
+          fi
+          echo "Success rate of provisioning requests: $SUCCESS_RATE%" >> $GITHUB_STEP_SUMMARY
+          
+          kill $(cat /tmp/metrics_pid) || echo "Metrics script not running"
+          METRICS_FILE="/tmp/keb_metrics.jsonl"
+
+          jq -s '
+          {
+            goroutines: map(.goroutines),
+            open_fds: map(.open_fds),
+            db_idle: map(.db_idle),
+            db_max_open: map(.db_max_open),
+            db_in_use: map(.db_in_use),
+            mem_alloc: map(.mem_alloc),
+            mem_stack: map(.mem_stack),
+            mem_heap: map(.mem_heap)
+          }' "$METRICS_FILE" > /tmp/aggregated_metrics.json
+
+          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
+          echo "xychart-beta title \"Goroutines\" line \"Goroutines\" [$(jq -r '.goroutines | @csv' /tmp/aggregated_metrics.json)]" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
+          echo "xychart-beta title \"Open FDs\" line \"open_fds\" [$(jq -r '.open_fds | @csv' /tmp/aggregated_metrics.json)]" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
+          echo "xychart-beta title \"Go Memstats\" y-axis \"Memory (in MiB)\" line \"Alloc\" [$(jq -r '.mem_alloc | @csv' /tmp/aggregated_metrics.json)] line \"Heap\" [$(jq -r '.mem_heap | @csv' /tmp/aggregated_metrics.json)] line \"Stack\" [$(jq -r '.mem_stack | @csv' /tmp/aggregated_metrics.json)]" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo "<div align=\"center\">" >> "$GITHUB_STEP_SUMMARY"
+          echo "" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Color | Type               |" >> "$GITHUB_STEP_SUMMARY"
+          echo "|-------|--------------------|" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Green | Heap in use bytes  |" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Blue  | Alloc bytes        |" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Red   | Stack in use bytes |" >> "$GITHUB_STEP_SUMMARY"
+          echo "</div>" >> "$GITHUB_STEP_SUMMARY"
+          echo "" >> "$GITHUB_STEP_SUMMARY"
+
+          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
+          echo "xychart-beta title \"DB Connections\" line \"Idle\" [$(jq -r '.db_idle | @csv' /tmp/aggregated_metrics.json)] line \"In Use\" [$(jq -r '.db_in_use | @csv' /tmp/aggregated_metrics.json)] line \"Max Open\" [$(jq -r '.db_max_open | @csv' /tmp/aggregated_metrics.json)]" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo "<div align=\"center\">" >> "$GITHUB_STEP_SUMMARY"
+          echo "" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Color | Type     |" >> "$GITHUB_STEP_SUMMARY"
+          echo "|-------|----------|" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Red   | Max open |" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Blue  | Idle     |" >> "$GITHUB_STEP_SUMMARY"
+          echo "| Green | In use   |" >> "$GITHUB_STEP_SUMMARY"
+          echo "</div>" >> "$GITHUB_STEP_SUMMARY"
+          echo "" >> "$GITHUB_STEP_SUMMARY"
