wip

diff --git a/.github/workflows/run-performance-tests-reusable.yaml b/.github/workflows/run-performance-tests-reusable.yaml
--- a/.github/workflows/run-performance-tests-reusable.yaml
+++ b/.github/workflows/run-performance-tests-reusable.yaml
@@ -751,6 +751,29 @@ jobs:
 
       - name: Prepare instances for update and deprovisioning
         run: |
+          # Instances for updating
+          seq 1 ${{ inputs.instances-number }} | xargs -n1 -P8 -I{} bash -c '
+            uid=$(uuidgen)
+            curl --silent --show-error --fail --request PUT \
+              --url "http://localhost:8080/oauth/v2/service_instances/$uid" \
+              --header "Content-Type: application/json" \
+              --header "X-Broker-API-Version: 2.16" \
+              --data "{\"service_id\":\"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\"plan_id\":\"8cb22518-aa26-44c5-91a0-e669ec9bf443\",\"context\":{\"globalaccount_id\":\"2f5011af-2fd3-44ba-ac60-eeb1148c2995\",\"subaccount_id\":\"8b9a0db4-9aef-4da2-a856-61a4420b66fd\",\"user_id\":\"user@email.com\"},\"parameters\":{\"name\":\"azure-lite-cluster\",\"region\":\"northeurope\"}}" > /dev/null 2>&1
+          '
+
+          TOTAL_COUNT=$(curl --request GET \
+            --url http://localhost:8080/runtimes?plan=azure_lite \
+            --header 'Content-Type: application/json' \
+            --header 'X-Broker-API-Version: 2.16' | jq .totalCount)
+
+          if [ "$TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+            echo "Assertion passed: totalCount is $TOTAL_COUNT"
+          else
+            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $TOTAL_COUNT"
+            exit 1
+          fi
+          
+          # Instances for deprovisioning
           seq 1 ${{ inputs.instances-number }} | xargs -n1 -P8 -I{} bash -c '
             uid=$(uuidgen)
             curl --silent --show-error --fail --request PUT \
@@ -779,16 +802,18 @@ jobs:
         run: |
           scripts/simulate_kim.sh
           
+          INSTANCES_NUMBER=$(( 2 * ${{ inputs.instances-number }} ))
+          
           RESPONSE_JSON=$(curl --request GET \
-            --url "http://localhost:8080/runtimes?plan=azure&state=succeeded" \
+            --url "http://localhost:8080/runtimes?plan=azure,azure_lite&state=succeeded" \
             --header 'Content-Type: application/json' \
             --header 'X-Broker-API-Version: 2.16')
           SUCCEEDED_TOTAL_COUNT=$(echo "$RESPONSE_JSON" | jq .totalCount)
 
-          if [ "$SUCCEEDED_TOTAL_COUNT" -eq "${{ inputs.instances-number }}" ]; then
+          if [ "$SUCCEEDED_TOTAL_COUNT" -eq "$INSTANCES_NUMBER" ]; then
             echo "Assertion passed: totalCount is $SUCCEEDED_TOTAL_COUNT"
           else
-            echo "Assertion failed: totalCount is not ${{ inputs.instances-number }}. Actual value: $SUCCEEDED_TOTAL_COUNT"
+            echo "Assertion failed: totalCount is not $INSTANCES_NUMBER. Actual value: $SUCCEEDED_TOTAL_COUNT"
             exit 1
           fi
 
