Check status

diff --git a/.github/workflows/run-helm-template-reusable.yaml b/.github/workflows/run-helm-template-reusable.yaml
--- a/.github/workflows/run-helm-template-reusable.yaml
+++ b/.github/workflows/run-helm-template-reusable.yaml
@@ -65,17 +65,38 @@ jobs:
           kubectl create namespace kyma-system
           kubectl create namespace istio-system
 
-     
+      - name: Install istio
+        run: |
+          helm repo add istio https://istio-release.storage.googleapis.com/charts
+          helm install istio-base istio/base -n istio-system --set defaultRevision=default
 
       - name: Apply helm chart
         run: |
           cd resources/keb
           helm template . | kubectl apply -f -
-
+  
+  check-e2e-status:
+    needs: run-e2e-matrix
+    runs-on: ubuntu-latest
+    if: success() 
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        run: echo "::set-output name=success::true"
 
   finish-e2e-tests:
     runs-on: ubuntu-latest
-    needs: run-e2e-matrix
+    if: always()
+    needs: [run-e2e-matrix, check-e2e-status]
     steps:
       - name: Final step
-        run: echo "All finished"
+        run: |
+          passed="${{ needs.check-e2e-status.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Shards passed"
+            exit 0
+          else
+            echo "Shards failed"
+            exit 1
+          fi
